# Generated by Django 5.0.1 on 2024-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('LS', 'Lassi'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('ML', 'Milk')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
